(function(global){
function signature(canvas){const ratio=window.devicePixelRatio||1;canvas.width=900*ratio;canvas.height=300*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.lineWidth=3;ctx.strokeStyle='#133b67';ctx.lineCap='round';let down=false,ink=false;const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*900/r.width,(e.clientY-r.top)*300/r.height]};canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);down=true;ctx.beginPath();ctx.moveTo(...point(e));e.preventDefault()};canvas.onpointermove=e=>{if(down){ctx.lineTo(...point(e));ctx.stroke();ink=true;e.preventDefault()}};canvas.onpointerup=canvas.onpointercancel=()=>down=false;return {clear(){ctx.clearRect(0,0,900,300);ink=false},value(){return ink?canvas.toDataURL('image/png'):''}}}
async function image(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('Image invalide'));i.src=src})}
async function pdf(frozen,signatureURI){const doc=await PDFLib.PDFDocument.create();doc.setTitle('Contrat '+frozen.record.numero);doc.setAuthor(frozen.settings.company_name||'Gestion Pro');let canvas,ctx,y,pageNo=0;const W=1240,H=1754,pages=[];function start(){canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#08284e';ctx.fillRect(0,0,W,170);ctx.font='bold 38px sans-serif';ctx.fillStyle='white';ctx.fillText(frozen.settings.company_name||'HAJ BEN ZIAN CAR',70,76);ctx.font='22px sans-serif';ctx.fillText('CONTRAT DE LOCATION · '+frozen.record.numero,70,121);y=215;pageNo++}function finish(){ctx.fillStyle='#718196';ctx.font='18px sans-serif';ctx.fillText('Gestion Pro • Copie figée lors de la signature • Page '+pageNo,70,H-50);pages.push(canvas.toDataURL('image/png'))}function next(){finish();start()}function line(text,bold=false,size=25){ctx.font=(bold?'bold ':'')+size+'px sans-serif';let words=String(text??'').replace(/\r/g,'').split(/\s+/),current='';for(const word of words){const test=current?current+' '+word:word;if(ctx.measureText(test).width>W-140&&current){draw(current);current=word}else current=test}if(current)draw(current);function draw(t){if(y>H-120)next();ctx.font=(bold?'bold ':'')+size+'px sans-serif';ctx.fillStyle=bold?'#08284e':'#263c52';ctx.fillText(t,70,y);y+=size+15}}function gap(n=15){y+=n}
start();let c=frozen.client,v=frozen.vehicle,r=frozen.record;line('CLIENT',true,29);line(c.nom+' '+c.prenom);line('Code : '+c.code+'    CIN : '+c.cin);line('Téléphone : '+(c.telephone||'—'));line('Adresse : '+(c.adresse||'—')+' '+(c.ville||''));line('Naissance : '+GP.french(c.date_naissance)+'    Permis : '+(c.permis||'—'));gap();line('VÉHICULE ET LOCATION',true,29);line(v.modele+'    Immatriculation : '+(v.immatriculation||'—'));line('Départ : '+GP.french(r.date_depart)+' à '+r.heure_depart);line('Retour : '+GP.french(r.date_retour)+' à '+r.heure_retour);line('Kilométrage actuel lors de la saisie : '+(frozen.current_km??v.compteur)+' km');line('Kilométrage de départ : '+r.km_depart+' km');gap();line('MONTANTS',true,29);line(r.duree+' jour(s) × '+r.prix+' DH / jour');line('Total : '+r.montant+' DH     Réglé : '+r.reglement+' DH     Reste : '+r.reste+' DH',true);gap();if(r.notes){line('OBSERVATIONS',true,29);line(r.notes);gap()}line('CONDITIONS DE LOCATION',true,29);for(const p of String(frozen.settings.general_conditions||'Conditions de la société à vérifier avant signature.').split('\n')){line(p,false,21)}gap();line('SIGNATURE DU CLIENT',true,29);if(signatureURI){const img=await image(signatureURI);if(y+180>H-120)next();ctx.drawImage(img,70,y,520,170);y+=180}else line('Contrat non signé',true);line('Établi le '+new Date(frozen.created_at).toLocaleString('fr-FR'),false,18);finish();for(const png of pages){const pic=await doc.embedPng(png);const page=doc.addPage([595.28,841.89]);page.drawImage(pic,{x:0,y:0,width:595.28,height:841.89})}return await doc.save()}
function toBase64(bytes){let out='';for(let i=0;i<bytes.length;i+=8192)out+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(out)}
function bytes(b64){return Uint8Array.from(atob(b64),c=>c.charCodeAt(0))}
function download(data,name,type='application/pdf'){let url=URL.createObjectURL(new Blob([data],{type}));let a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function phone(value){let p=String(value||'').replace(/\D/g,'');if(p.startsWith('00'))p=p.slice(2);if(p.length===10&&p[0]==='0')p='212'+p.slice(1);if(!/^[1-9]\d{7,14}$/.test(p))throw Error('Téléphone client absent ou invalide.');return p}
async function sharePDF(b64,name,number){const file=new File([bytes(b64)],name,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'Contrat de location',text:'Votre contrat de location'});return}phone(number);download(bytes(b64),name);window.open('https://wa.me/'+phone(number)+'?text='+encodeURIComponent('Bonjour, voici votre contrat de location. Je joins le PDF signé.'),'_blank','noopener');return 'Joignez le PDF téléchargé dans WhatsApp.'}
global.GPDoc={signature,pdf,toBase64,bytes,download,phone,sharePDF};
})(window);
